modLoader="javafml"
loaderVersion="[49,)"
issueTrackerURL="https://github.com/bigenergy/glassential-renewed/issues"
license="MIT License https://github.com/bigenergy/glassential-renewed/blob/master/LICENSE"

[[mods]]
modId="glassential"
version="${file.jarVersion}"
displayName="Glassential"
displayURL="https://curseforge.com/minecraft/mc-mods/glassential-renewed"
logoFile="logo.png"
credits="Extra Utilities 2 for the inspiration, MayusYT for the name, Wouter for the awesome logo, UpcraftLP for the Fabric maintain."
authors="Lykrast / Ported by Big_Energy"
description='''
Various glasses for all your decorative needs.
'''

[[dependencies.glassential]]
    modId="forge"
    mandatory=true
    versionRange="[49,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.glassential]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"